Fix - NotFound errors gracefully
EventStore/EventStore.UI pull request #324
Opened 2022-04-26 17:36 UTC by dhingrak

fixes: #285 

Before:
When the user clicks on ViewParkedMessages and the stream does not have any events or the stream does not exist
![PersistentSubscriptionParkedStream_Before](https://user-images.githubusercontent.com/25709924/165359053-c7bce02d-c813-430d-8a32-3cfc00286d9d.PNG)

After:
![PersistentSubscriptionParkedStream_After](https://user-images.githubusercontent.com/25709924/165359124-4934e833-4c68-4f61-9679-041e223b55fc.PNG)

Before:
The deleted stream in a stream browser shows an alert popup with Not Found
![DeletedStreamBefore](https://user-images.githubusercontent.com/25709924/165359377-30eeb3a3-1462-4297-a23c-d43bdfb73979.PNG)

After: 
![DeletedStream](https://user-images.githubusercontent.com/25709924/165359457-18e2aea5-8024-4167-a0d9-b66a9a6cf600.PNG)

2022-04-28 16:55 UTC, thefringeninja approved these changes

2022-04-29 11:08 UTC, hayley-jean requested changes
The changes look good, I've just made some suggestions to improve the messages for when events aren't found

2022-04-29 11:08 UTC, hayley-jean commented on src/js/modules/competing/views/subscriptions.item.viewparkedmessages.tpl.html
> +			<em>No parked events for current path: {{ $stateParams | json }}
```suggestion
			<em>No parked events for subscription {{streamId}}::{{groupName}}
```

2022-04-29 11:08 UTC, hayley-jean commented on src/js/modules/streams/views/streams.item.events.tpl.html
>  				<em>No events for current path: {{ $stateParams | json }}
```suggestion
				<em>No events for stream: {{ streamId }}
```

2022-04-29 14:55 UTC, dhingrak commented on src/js/modules/streams/views/streams.item.events.tpl.html
>  				<em>No events for current path: {{ $stateParams | json }}
Changes Done

2022-05-02 12:21 UTC, hayley-jean approved these changes

2022-05-02 12:22 UTC, merged