Upgrade NodeJS to v18.12.1 LTS, gulp to v4, replace node-sass with sass
EventStore/EventStore.UI pull request #338
Opened 2022-11-20 20:42 UTC by 321zer0

This commit bumps NodeJS to v18.12.1 LTS, upgrades gulp v3.9.1 to v4.0.0, and replaces node-sass which has been deprecated with sass.

2022-11-20 20:53 UTC, 321zer0 commented
CI Build is failing because GitHub Actions is using node `v10.24.1` instead of `v18.12.1`.

2022-11-22 14:26 UTC, thefringeninja commented
You'll have to go through all the workflow files and update the node version to use.

2022-12-01 14:34 UTC, 321zer0 commented
@thefringeninja Workflow files have been updated. I've also updated `gulpfile.js` to accommodate the breaking changes in gulp v4.0.0

2022-12-01 16:29 UTC, thefringeninja requested changes

2022-12-01 16:29 UTC, thefringeninja commented on .github/workflows/ci.yml
>          uses: actions/checkout@v2
Don't forget to upgrade this action to v3

2022-12-01 16:29 UTC, thefringeninja commented on .github/workflows/ci.yml
>          uses: actions/setup-node@v1
same thing here

2022-12-02 11:10 UTC, 321zer0 commented
@thefringeninja I've updated the actions to v3. Also bumped bower to v1.8.14 to bower which patches an arbitrary file write security vulnerability: https://snyk.io/blog/severe-security-vulnerability-in-bowers-zip-archive-extraction/

2022-12-02 17:00 UTC, thefringeninja approved these changes

2022-12-06 16:42 UTC, hayley-jean requested changes
It looks like `iconv-lite` needs to be added as a dependency, but after installing that it works on my side

Could you also update the readme with the new installation and run steps please?

2022-12-09 11:54 UTC, 321zer0 commented
@hayley-jean I've updated the setup instructions in the `README` to use `NodeJS v18.12.1`.
I also tested the setup on a Linux distro and all the `gulp` commands worked well; I didn't have to install the `iconv-lite` package.

2022-12-12 15:14 UTC, hayley-jean approved these changes
Using the updated version of npm resolved the issue, thanks 👍

2022-12-12 15:16 UTC, merged