[ESDB-155] Add banner for EventStore Navigator
EventStore/EventStore.UI pull request #366
Opened 2024-06-24 16:01 UTC by dhingrak

Added: https://eventstore.aha.io/develop/features/ESDB-155

2024-06-25 11:57 UTC, hayley-jean requested changes

2024-06-25 11:57 UTC, hayley-jean commented on src/css/main.css
> +.navigator-banner-header {
The css files for the legacy UI are auto-generated, so these changes will be overridden when the automation next runs. You need to make the changes in the sass files for it to stick. The [module-siteheader.scss](https://github.com/EventStore/EventStore.UI/blob/master/src/scss/_module-siteheader.scss) would be the most appropriate place for this

2024-06-25 12:55 UTC, dhingrak commented on src/css/main.css
> +.navigator-banner-header {
Okay. I will make the changes.

2024-06-28 11:24 UTC, hayley-jean requested changes

2024-06-28 11:24 UTC, hayley-jean commented on src/views/index.tpl.html
> +		<a href="https://cloudsmith.io/~eventstore/repos/navigator/packages/">Admin UI is legacy, and it's being replaced by EventStore Navigator. <b>Click here</b> to download EventStore Navigator</a>
The link should be to the docs-next page:
```suggestion
		<a href="https://docs-next.eventstore.com/navigator/">Admin UI is legacy, and it's being replaced by EventStore Navigator. <b>Click here</b> to download EventStore Navigator</a>

```

2024-07-01 09:29 UTC, hayley-jean approved these changes

2024-07-01 09:29 UTC, merged